In [1]:
import pandas as pd
df=pd.read_csv('cars.csv')

In [2]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8128 entries, 0 to 8127
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   brand          8128 non-null   object
 1   km_driven      8128 non-null   int64
 2   fuel           8128 non-null   object
 3   owner          8128 non-null   object
 4   selling_price  8128 non-null   int64
dtypes: int64(2), object(3)
memory usage: 317.6+ KB

In [4]:
df.describe()

          km_driven  selling_price
count  8.128000e+03   8.128000e+03
mean   6.981951e+04   6.382718e+05
std    5.655055e+04   8.062534e+05
min    1.000000e+00   2.999900e+04
25%    3.500000e+04   2.549990e+05
50%    6.000000e+04   4.500000e+05
75%    9.800000e+04   6.750000e+05
max    2.360457e+06   1.000000e+07

In [5]:
df.duplicated().sum()

np.int64(1678)

In [9]:
df.select_dtypes(include='number').corr()

               km_driven  selling_price
km_driven       1.000000      -0.225534
selling_price  -0.225534       1.000000

In [10]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

# One Hot Encoding using pandas

In [13]:
pd.get_dummies(df , columns=['fuel','owner'] , drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

# k-1 one hot encoding using scikit learn

In [14]:
from sklearn.model_selection import train_test_split

In [17]:
xtr,xts,ytr,yts=train_test_split(df.drop('selling_price',axis=1) , df['selling_price'] , test_size=0.2 , random_state=2)

In [28]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first' , sparse_output=False , dtype=np.int32)

In [30]:
xtr_new=ohe.fit_transform(xtr[['fuel','owner']])

In [31]:
xts_new=ohe.transform(xts[['fuel','owner']])

In [32]:
import numpy as np
np.hstack((xtr[['brand','km_driven']].values,xtr_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

# one hot encoder with top categories

In [36]:
count=df['brand'].value_counts()

In [38]:
df['brand'].nunique()
threshold = 100

In [39]:
repl = counts[counts <= threshold].index

In [40]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
6362,False,False,False,False,False,False,True,False,False,False,False,False,False
6387,False,False,False,False,False,False,True,False,False,False,False,False,False
7284,False,False,False,True,False,False,False,False,False,False,False,False,False
4189,False,False,False,False,True,False,False,False,False,False,False,False,False
642,False,False,False,False,False,True,False,False,False,False,False,False,False