In [1]:
import pandas as pd

In [4]:
df=pd.read_csv('customer.csv')

In [5]:
df.head()

   age  gender   review education purchased
0   30  Female  Average    School        No
1   68  Female     Poor        UG        No
2   70  Female     Good        PG        No
3   72  Female     Good        PG        No
4   16  Female  Average        UG        No

In [6]:
df=df.iloc[:,2:]

In [11]:
df.tail()

   review education purchased
45   Poor        PG       Yes
46   Poor        PG        No
47   Good        PG       Yes
48   Good        UG       Yes
49   Good        UG        No

In [9]:
df.size

150

# ordinal encoding

In [38]:
from sklearn.model_selection import train_test_split as tts
xtr,xts,ytr,yts=tts(df.drop('purchased' , axis=1) , df['purchased'] , test_size=0.2 , random_state=0)

In [39]:
xtr.shape , xts.shape

((40, 2), (10, 2))

In [40]:
from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])
xtr=oe.fit_transform(xtr)
xts=oe.transform(xts)

In [42]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [43]:
xtr=pd.DataFrame(xtr)

In [32]:
xtr

      0    1
0   2.0  2.0
1   0.0  0.0
2   0.0  2.0
3   1.0  0.0
4   2.0  0.0
5   0.0  0.0
6   0.0  2.0
7   0.0  2.0
8   2.0  1.0
9   1.0  1.0
10  0.0  1.0
11  1.0  1.0
12  1.0  1.0
13  0.0  1.0
14  2.0  2.0
15  1.0  0.0
16  0.0  2.0
17  1.0  1.0
18  1.0  0.0
19  2.0  0.0
20  1.0  0.0
21  0.0  1.0
22  2.0  0.0
23  2.0  1.0
24  0.0  1.0
25  0.0  0.0
26  1.0  2.0
27  1.0  2.0
28  2.0  0.0
29  2.0  0.0
30  2.0  1.0
31  1.0  2.0
32  0.0  2.0
33  2.0  1.0
34  0.0  2.0
35  0.0  2.0
36  2.0  2.0
37  1.0  0.0
38  2.0  2.0
39  1.0  1.0

In [44]:
xts=pd.DataFrame(xts)

In [45]:
xts

     0    1
0  0.0  0.0
1  2.0  1.0
2  2.0  1.0
3  2.0  2.0
4  2.0  2.0
5  0.0  2.0
6  2.0  0.0
7  0.0  0.0
8  0.0  2.0
9  1.0  1.0